- name: Install Docker and run HTTP script container
  hosts: all
  become: true

  vars:
    project_url: "https://github.com/Imyourstuff/test.git"
    image_name: yadro
    container_name: yadro
    app_path: /opt/yadro

  tasks:
    - name: Localhost or Inventory
      set_fact:
        is_local: "{{ inventory_hostname == 'localhost' }}"

    - name: Set package names based on OS
      set_fact:
        docker_pkg: "{{ 'docker' if ansible_os_family == 'Archlinux' else 'docker.io' }}"

    # Заменил на универсальную штуку вместо apt и pacman, разные имена в ubuntu и арче для докера
    # Ломают скрипт
    - name: Install packages for work
      package:
        name:
          - ca-certificates
          - curl
          - git
          - "{{docker_pkg}}"
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Check docker version
      command: docker --version
      register: docker_version
    
    - name: Check for docker installation
      debug:
        var: docker_version.stdout

    - name: Create app directory
      file:
        path: "{{app_path}}"
        state: directory

    # Пробуем подтянуть актуальные файлы c Git
    - name: Copy project files from GitHub
      ansible.builtin.git:
       repo: "{{project_url}}"
       dest: "{{app_path}}"
       version: main
       force: yes

    # Костыль страшно
    - name: Extracting from folders
      shell: mv {{ app_path }}/3/* {{ app_path }}/

    # Собираем и запускаем контейнер
    - name: Build docker image
      shell: docker build -t {{image_name}} {{app_path}}
        
    # Обход уже существующего контейнера
    - name: Check if container already exists
      command: docker ps -a --filter "name=^{{ container_name }}$" --format "{{ '{{.Names}}' }}"
      register: container_check
      changed_when: false

    - name: Start existing container if stopped
      command: docker start {{ container_name }}
      when: container_check.stdout == container_name

    - name: Run new container if not exists
      shell: docker run -d --name {{ container_name }} {{ image_name }}
      when: container_check.stdout != container_name

    - name: Wait for container to finish
      command: docker wait {{ container_name }}
      register: container_exit

    # Логи
    - name: Get container logs
      command: docker logs {{ container_name }}
      register: logs

    - name: Print logs!
      debug:
        var: logs.stdout

    # Проверка
    - name: Check
      fail:
        msg: "Container failed"
      when: container_exit.stdout != "0"

    - name: What?
      debug:
        msg: "Playbook finished."